import Image from "next/image";
import s from "./MajorCardSlider.module.css";

export default function MajorCardSlider() {
  return (
    <div className={s.slider}>
      <div className={s.slides}>
        <Image
          src="/cards/0.건축학.svg"
          alt="건축학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/1.토목공학.svg"
          alt="토목공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/2.도시공학.svg"
          alt="도시공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/3.소방방재학.svg"
          alt="소방방재학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/4.전산학컴퓨터공학.svg"
          alt="전산학컴퓨터공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/5.산업공학.svg"
          alt="전산학컴퓨터공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/6.게임공학.svg"
          alt="게임공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/7.재료공학.svg"
          alt="재료공학"
          width={180}
          height={250}
        />
        <Image src="/cards/8.화학.svg" alt="화학" width={180} height={250} />
        <Image
          src="/cards/9.화학공학.svg"
          alt="화학공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/10.나노신소재공학.svg"
          alt="나노신소재공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/11.전기공학.svg"
          alt="전기공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/12.전자공학.svg"
          alt="전자공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/0.건축학.svg"
          alt="건축학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/1.토목공학.svg"
          alt="토목공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/2.도시공학.svg"
          alt="도시공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/3.소방방재학.svg"
          alt="소방방재학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/4.전산학컴퓨터공학.svg"
          alt="전산학컴퓨터공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/5.산업공학.svg"
          alt="전산학컴퓨터공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/6.게임공학.svg"
          alt="게임공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/7.재료공학.svg"
          alt="재료공학"
          width={180}
          height={250}
        />
        <Image src="/cards/8.화학.svg" alt="화학" width={180} height={250} />
        <Image
          src="/cards/9.화학공학.svg"
          alt="화학공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/10.나노신소재공학.svg"
          alt="나노신소재공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/11.전기공학.svg"
          alt="전기공학"
          width={180}
          height={250}
        />
        <Image
          src="/cards/12.전자공학.svg"
          alt="전자공학"
          width={180}
          height={250}
        />
      </div>
    </div>
  );
}
